POST /properties?f=json HTTP/1.1
Content-Length: 364
Content-Type: application/sml+json
Host: localhost:5000
User-Agent: HTTPie

{
  "id": "AverageCpuTemp",
  "uniqueId": "urn:example:property:avg-cpu-temp",
  "label": "Average CPU Temp",
  "description": "Hourly average of the CPU temperature",
  "baseProperty": "http://qudt.org/vocab/quantitykind/Temperature",
  "object": "http://dbpedia.org/resource/Central_processing_unit",
  "statistic": "http://sensorml.com/ont/x-stats/HourlyMean"
}